### ISSUE TITLE
Unable to start ClickHouse cluster using UI on GKE with Kubernetes v 1.20

### ISSUE THREAD

**Issue by hodgesrm** [Altinity/altinity-dashboard#49]
I'm unable to start a ClickHouse cluster from YAML via the UI after installing ClickHouse Operator 0.16.1.  Latest git hash is: 
```
commit 18a7e6981da2640fcc428b05b4bbc6fa67f809ad (HEAD -> main, origin/main, origin/HEAD)
Author: Graham Mainwaring <graham@mhn.org>
Date:   Mon Dec 6 18:35:28 2021 -0500

    Add editing of CHIs
```
Steps to reproduce

1. Run `./adash --bindhost 0.0.0.0 -devmode -debug -notoken` and login with browser.  Environment has .kube/config set to work with GKE. 
2. Go to "Operators" and use + sign to install 0.16.1 operator in default namespace. 
3. After operator is running, go to ClickHouse Installations tab and press + to upload definition.  Add the following code and deply to the default namespace:
```
apiVersion: "clickhouse.altinity.com/v1"
kind: "ClickHouseInstallation"
metadata:
  name: "simple-01"
spec:
  configuration:
    clusters:
      - name: "cl"
        layout:
          shardsCount: 1
          replicasCount: 1
        templates:
          podTemplate: clickhouse-stable
          volumeClaimTemplate: storage-vc-template
  templates:
    podTemplates:
      - name: clickhouse-stable
        spec:
          containers:
          - name: clickhouse
            image: altinity/clickhouse-server:21.8.10.1.altinitystable
    volumeClaimTemplates:
      - name: storage-vc-template
        spec:
          storageClassName: standard
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 1Gi
```
4. Installation fails with the following error message: Error deploying CHI: Error: Error creating CHI: no matches for kind "ClickHouseInstallation" in version "clickhouse.altinity.com/v1"

This failure only occurs for me on GKE. Step three works if I do the following:

1. Run everything on minikube.  It works great. 
2. Run `kubectl apply -f file-with-above-yaml.yaml`
